media: 
  input: src/images
  output: docs/images
content:
  - name: courses
    label: Courses 
    type: collection
    path: src/courses
    fields: 
      - { name: CourseName, label: Course Name, type: string }
      - name: Programs
        label: programs
        type: select
        options:
          multiple: true
          values: [IB, HSM]
  