media: 
  input: src/images
  output: docs/images
content:
  - name: courses
    label: Courses 
    type: collection
    path: src/courses
    view: 
      fields: [ CourseName, DevCycle ]
      sort: DevCycle
      order: desc
    fields: 
      - { name: CourseName, label: Course Name, type: string }
      - name: Programs
        label: programs
        type: select
        options:
          multiple: true
          values: [IB, HSM]
      - { name: DevCycle, label: Development Cycle, type: number }
      - { name: Blueprint, label: Blueprint, type: string }
      - { name: Description, label: Course Description, type: rich-text }
      - name: Team
        label: Team
        type: object
        list: true
        fields: 
          - name: Name
            label: Name
            type: string
          - name: Role
            label: Role
            type: select
            options: 
              values: [Course Author, Learning Designer, Digital Education Developer]
          - name: Involvement
            label: Involvement
            type: select
            options: 
              values: [Lead, Collaborator, Contributer]
      - name: CLOs
        label: Course Learning Outcomes
        type: text
        list: true
        options: 
          rows: 3
      - name: Topics
        label: Topics
        type: text
        list: true
        options: 
          autoresize: true
      - name: Assessments
        label: Assessments
        type: object
        list: true
        fields: 
          - { name: Name, label: Name, type: string }
          - { name: Weighting, label: Weighting, type: number }
          - name: Type
            label: Type
            type: select 
            list: true
            options:
              multiple: true
              values: ["Annotated Bibliography","Assessment Plan","Case Study","Concept Design","Creative Work","Critical Analysis","Data Collection and/or Analysis","Design Project","Discussion","Essay","Interactive Questions","Interview","Learning Journal","Linguistics Exercise","Literature Review","Media Task","Model","Multiple Choice Questions","Oral Defence","Peer Review","Performance","Persuasive Piece","Placement or Workplace-based Assessment","Portfolio","Problem Solving","Professional Simulation","Proposal","Report","Short Response Questions","Skills Demonstration","Thesis"]